[ENP-820] Blackbox Exporter Enhanced
devnetmonk/blackbox_exporter pull request #3
Opened 2024-02-20 06:32 UTC by ArieDeha

### Prometheus Blackbox Exporter on **dope** !

**Focused Files:**
- main.go
- config/config.go
- probe/icmp_qos.go
- probe/icmp_qos_test.go

Other files mostly are cleaning up “Unhandled error” and “whitespaces”

**DoD:**
Forked from prometheus blackbox exporter

**Add QoS Feature**
Create Test and Coverage for QoS

**ScreenShots:**
- Coverage Test 93%
![image](https://github.com/devnetmonk/blackbox_exporter/assets/9045281/f8fc4d5a-8bb0-4d03-9b13-55e585ff8a4a)
- Results
![image](https://github.com/devnetmonk/blackbox_exporter/assets/9045281/88d12450-8d30-4bfd-bf8c-6d1e3cafa260)

**Commits**:
- [[ENP-820] Forked Prometheus Blackbox Exporter; Add QoS Features; Add Test and Coverage](https://github.com/devnetmonk/blackbox_exporter/commit/0085d3f262bd81fc6863f7eead6bde2f6913dcc3)
- [merge conflict: from latest prometheus](https://github.com/devnetmonk/blackbox_exporter/commit/989af2d979f2f988c41dffe19361f97f655c7c54)
- [cleanups and tidying go mod](https://github.com/devnetmonk/blackbox_exporter/commit/e6ba56a5e2ee39aed37164d556e4d9166171067c)

2024-02-21 08:34 UTC, adhimaswaskita requested changes

2024-02-21 08:34 UTC, adhimaswaskita commented on prober/icmp_qos.go
> +		if probeQoSPacketLossReceived > 0 {
mas aried, pengambilan min, max, avg stddev latency ngga dari result pingernya aja langsung ? 
https://github.com/prometheus-community/pro-bing/blob/v0.3.0/ping.go#L258

2024-02-21 08:34 UTC, adhimaswaskita commented on prober/icmp_qos.go
> +		jitter = prevTime - float64(pkt.Rtt.Nanoseconds())/perThousand
ini kebalik ngga si mas ? kalo perhitungan pertama bukannya hasilnya jadi negative ?

2024-02-21 08:34 UTC, adhimaswaskita commented on prober/icmp_qos.go
> +		Name: "probe_qos_latency_gauge",
metrics name disesuaikan dengan yang ada di RFC

2024-02-21 08:34 UTC, adhimaswaskita commented on prober/icmp_qos.go
> +		Name: "probe_qos_packet_loss",
ini juga metrics name disesuaikan dengan yang ada di RFC

2024-02-21 08:34 UTC, adhimaswaskita commented on prober/icmp_qos.go
> +		probeQoSDurationSecondsSecond float64
variable namingnya menurutku better langsung probeQoSDurationSeconds dengan perubahan variable naming metrics pake suffix metrics, atau  langsung probeQoSDurationSecondsValue. cmiiw

2024-02-21 08:34 UTC, adhimaswaskita commented on prober/icmp_qos.go
> +		probeQoSDurationSecondsSecond = float64(totalDuration.Microseconds()) / (perThousand * perThousand)
ini bisa langsung pake .Miliseconds / 1000

2024-02-26 06:48 UTC, ArieDeha commented on prober/icmp_qos.go
> +		if probeQoSPacketLossReceived > 0 {
done, on next commit

2024-02-26 06:49 UTC, ArieDeha commented on prober/icmp_qos.go
> +		jitter = prevTime - float64(pkt.Rtt.Nanoseconds())/perThousand
done, on next commit, dgn catetan, in a way, akan dibalik juga di line berikutnya klo hasilnya negative... expected memang akan ada nilai negative...

2024-02-26 06:51 UTC, ArieDeha commented on prober/icmp_qos.go
> +		Name: "probe_qos_latency_gauge",
done, salah baca di rfc nya... on next commit

2024-02-26 06:52 UTC, ArieDeha commented on prober/icmp_qos.go
> +		Name: "probe_qos_packet_loss",
done... kebalik sama yg diatas

2024-02-26 06:53 UTC, ArieDeha commented on prober/icmp_qos.go
> +		probeQoSDurationSecondsSecond float64
di remove karena ambil lsg aja, ga jadi pakai converter. done on next commit

2024-02-26 06:54 UTC, ArieDeha commented on prober/icmp_qos.go
> +		probeQoSDurationSecondsSecond = float64(totalDuration.Microseconds()) / (perThousand * perThousand)
duration lsg pakai .Seconds() karena lsg, udh float64

2024-02-26 06:54 UTC, ArieDeha commented on prober/icmp_qos.go
> +		probeQoSDurationSecondsSecond = float64(totalDuration.Microseconds()) / (perThousand * perThousand)
done on next commit

2024-02-26 07:49 UTC, ArieDeha commented
@adhimaswaskita Updated on commit: https://github.com/ArieDeha/blackbox_exporter/commit/3dffca3e98f80dd5ebab14eb0563b5a332632c61

2024-02-29 02:13 UTC, adhimaswaskita requested changes
fmt.Printf diremove mas @ArieDeha , atau ada perlu di print ?

2024-03-05 04:19 UTC, ArieDeha commented
@adhimaswaskita udah yakkk!!

2024-03-05 04:34 UTC, adhimaswaskita approved these changes

2024-10-13 12:46 UTC, ganiamri commented
LGTM thanks mas @ArieDeha

2024-10-13 12:46 UTC, merged